config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'checktimes#new' 
  resources :alarms
  resources :checktimes
  resources :description
  root to: "home#index"
  get 'logout' => 'logout#index'
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checktime.rb
class Checktime < ApplicationRecord
  validates :plan, presence: true
  validates :month, presence: true
  validates :day, presence: true
  validates :hour, presence: true
  validates :minute, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'date'
  def after_sign_out_path_for(resource)
    logout_path 
  end
end

app/controllers/checktimes_controller.rb
class ChecktimesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create, :edit, :update, :destroy]
  def index
  end  
  
  def new
    @checktime = Checktime.new 
    @checktimes = Checktime.all
    if user_signed_in?
      @user_checktimes = Checktime.where(user_id: current_user.id)
    end  
    gon.checktimes = @checktimes
    gon.checktime = @checktimes
    gon.user_checktimes = @user_checktimes
    if user_signed_in?
      gon.current_user_id = current_user.id
    end
  end  

  def create
    @checktime = Checktime.new(checktime_params) 
     time = Time.now
     s_time = time.to_i
     plan = time.change(year:2020, month:@checktime.month, day:@checktime.day, hour:@checktime.hour, min:@checktime.minute, sec: 0 ) 
     s_plan = plan.to_i
     @checktime.total_sec = s_plan - s_time
     @checktime.user_id = current_user.id
     if @checktime.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json
      end
      else
      redirect_to root_path 
      end
  end

  def show
    @checktime = Checktime.find(params[:id])    
    @checktimes = Checktime.all
    gon.checktime = @checktime
    gon.checktimes = @checktimes
  end  

  def edit
    @checktime = Checktime.find(params[:id])
  end  

  def update 
    @checktime = Checktime.find(params[:id])
    @checktime.update(checktime_params)
    redirect_to root_path, data: {confirm: "更新しました"}
  end

  def destroy
    @checktime = Checktime.find(params[:id])    
    if @checktime.destroy
      redirect_to root_path
    else
      redirect_to root_path 
    end
  end 

  private

  def checktime_params
      params.require(:checktime).permit(:plan, :month, :day, :hour, :minute, :memo)
  end
end

  
  
  
   
  

app/controllers/description_controller.rb
class DescriptionController < ApplicationController
  def index
    @checktimes = Checktime.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  def index
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/checktimes_helper.rb
module ChecktimesHelper
end

app/helpers/description_helper.rb
module DescriptionHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/views/checktimes/edit.html.haml
.base
  .title
    checker
  .edit_form_box
    = form_for @checktime, url: checktime_path, method: :patch do |f|
      .e_msg 
        変更する内容を入力してください
      .text_box
        予定
        = f.text_field :plan, maxlength: 14
      .memo_box
        MEMO
        = f.text_area :memo
      .date
        日時#{@ccc}
        #{@c_date}  
        #{@ttt}
        #{@rrr}
      .submit_box
        = f.number_field :month, min: 1, max: 12
        月
        = f.number_field :day, min: 1, max: 31
        日
        = f.number_field :hour, min: 0, max: 23
        時
        = f.number_field :minute, min: 0, max: 59
        分
        = f.submit "予定を変更", class: 'btn' 
  .msg
    
   

app/views/checktimes/new.html.haml
.base
  .title
    checker
  = link_to description_index_path do  
    .use_btn
      使い方を見る 
  .registration_box     
    .user_registration                    
      = link_to "◇ユーザー登録", new_user_registration_path
    .user_registration  
      = link_to "◇ログイン", new_user_session_path
    .user_registration    
      = link_to "◇ログアウト", destroy_user_session_path, method: "delete", data:{confirm: "ログアウトします"}
    
        
  .form_box
    = form_for @checktime, url: alarms_path, method: :post do |f|
      .p_msg
        予定を入力してください
      .text_box
        予定
        = f.text_field :plan, maxlength: 14
      .memo_box
        MEMO
        = f.text_area :memo
      .date
        日時#{@ccc}
        #{@c_date}  
        #{@ttt}
        #{@rrr}
      .submit_box
        = f.number_field :month, min: 1, max: 12
        月
        = f.number_field :day, min: 1, max: 31
        日
        = f.number_field :hour, min: 0, max: 23
        時
        = f.number_field :minute, min: 0, max: 59
        分
        = f.submit "スタート", class: 'btn' 
  -if user_signed_in?
    .plans_title  
      現在の予定
      = @user_checktimes.count 
      件      
    .plans_base
      - @user_checktimes.each_with_index do |n, index| 
        .plans{"data-id" => "#{n.id}"}
          .plans_name{:id => "plans_#{index}"}
            = link_to "checktimes/#{n.id}" do
              #{n.plan}
          .plans_time
            #{n.month}月#{n.day}日&nbsp;#{n.hour}:#{n.minute}
            = link_to  "checktimes/#{n.id}/edit" do
              .edit_btn
                この予定を変更
            = link_to "checktimes/#{n.id}", method: :delete, data:{confirm: "削除しますか？"} do
              .remove_btn
                この予定を削除
        .check_msg{:id => "check_msg_#{index}"}        
          %input#hidden1{:type => "hidden", :value => "予定の時間が近づいています"}/ 
          %input#hidden2{:type => "hidden", :value => "予定の時間を過ぎています"}/ 
  
  -else   
    .logout_user


                      

app/views/checktimes/show.html.haml
.base 
  .title
    checker
  = link_to root_path  do
    .add_btn
      予定一覧を見る  
.main 
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#{@checktime.plan}&nbsp;&nbsp;&nbsp;&nbsp;#{@checktime.month}月#{@checktime.day}日#{@checktime.hour}時#{@checktime.minute}分
  - necessary_day = @checktime.total_sec / (24*60*60)
  - necessary_hour = (((@checktime.total_sec / (24*60*60).to_f) - (@checktime.total_sec / (24*60*60))) * 24).floor
  - necessary_min = (((((@checktime.total_sec / (24*60*60).to_f) - (@checktime.total_sec / (24*60*60))) * 24) -  (((@checktime.total_sec / (24*60*60).to_f) - (@checktime.total_sec / (24*60*60))) * 24).floor) * 60).floor
  - necessary_sec = (((((((@checktime.total_sec / (24*60*60).to_f) - (@checktime.total_sec / (24*60*60))) * 24) -  (((@checktime.total_sec / (24*60*60).to_f) - (@checktime.total_sec / (24*60*60))) * 24).floor) * 60) - necessary_min) * 60).floor
  .contents
    .contents_bar
      .al_bar
      .start_point
        start
      .space
      .over_point
        timeover
      %input#hidden3{:type => "hidden", :value => "予定の時間が近づいています"}/  
      %input#hidden4{:type => "hidden", :value => "予定の時間を過ぎています"}/  
    .contents_w
      .contents_left
        &nbsp;&nbsp;&nbsp;&nbsp;MEMO
        .s_memo
          = simple_format(@checktime.memo)
      #contents_right 
  .msg_alarm   
    = link_to  "#{@checktime.id}/edit" do
      .show_edit_btn
        この予定を変更
    = link_to "#{@checktime.id}", method: :delete, data:{confirm: "削除しますか？"} do    
      .show_remove_btn 
        この予定を削除            

app/views/description/index.html.haml
.base
  .title
    checker 
  .registration_box     
    .user_registration                    
      = link_to "◇ユーザー登録", new_user_registration_path
    .user_registration  
      = link_to "◇ログイン", new_user_session_path
    .user_registration    
      = link_to "◇ログアウト", destroy_user_session_path, method: "delete", data:{confirm: "ログアウトします"}
        
  .use_space  
    .use
      使い方の説明        
  .description   
    このアプリケーションはスケジュールを管理するアプリケーションです。
    .description_msg
      まずユーザー登録をクリックしてユーザー登録をしてください。
      %br
      %br
      ログイン後、入力欄に予定の名前や日時を入力して、スタートをクリックすると下の欄に予定が追加されます。
      %br
      日時は半角で入力してください
      %br
      %br
      予定の名前をクリックすると詳細を見ることができます。
      %br
      予定を削除したい場合は入力ページの予定の欄の「この予定を削除」ボタンをクリックします。
      %br
      予定を変更したい場合は入力ページの予定の欄の「この予定を変更」ボタンをクリックします。
      %br
      「予定一覧を見る」ボタンをクリックすると予定一覧ページへ移動します。 
  = link_to root_path, data: {"turbolinks" => false} do  
    .description_btn
      予定一覧を見る   
  .des_space
    
  

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Check
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = include_gon 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body
    = yield

app/views/logout/index.html.haml
.msg_box
  .msg
    ログアウトしました
    %br
    .back
      = link_to "戻る", new_checktime_path